jobs:
  create-logicapp-infra:
    env:
      AZURE_LOGICAPP_PACKAGE_PATH: .
      AZURE_SUBSCRIPTION: ad1e9f34-2525-4721-8777-445d89a891c7
      DEPLOY_ENV: ${{ matrix.azureenv }}
      DOTNET_VERSION: 3.1.301
      DPLOYMENT_NAME: TestlogicApp
      LOCATION: eastus2
      PARAMETERFILE_NAME: parameters.json
      RG_NAME: ''
      TEMPLATE_NAME: template.json
    environment: sandbox
    name: Create logicapp infra
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set the env variables according to env
      run: 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true

        echo "::set-env name=RG_NAME::$(cat .github/env/dev.env| grep RESOUECE_GROUP_NAME=
        | head -n 1 | grep -o ''".*"'' | sed ''s/"//g'')"

        echo ${{matrix.RG_NAME}}

        echo ${{matrix.azureenv}}

        echo $DEPLOY_ENV

        '
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - id: deploy
      uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ env.DPLOYMENT_NAME }}
        parameters: ${{ env.PARAMETERFILE_NAME }}
        resourceGroupName: ${{ env.RG_NAME }}
        template: ${{ env.TEMPLATE_NAME }}
    strategy:
      matrix:
        azureenv:
        - sandbox
name: Create azure infra for logic apps
'on':
  push:
    paths:
    - .github/workflows/logicapp_workflow.yaml
    - '*.json'
