jobs:
  create-logicapp-infra:
    env:
      DOTNET_VERSION: 3.1.301
    name: Create logicapp infra
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set the env variables according to env
      run: 'echo make executable set_env.sh

        chmod 755 .github/scripts/set_env.sh

        .github/scripts/set_env.sh ${{env.envtype}}

        echo ${{matrix.azureenv}}

        cat $GITHUB_ENV

        echo $DEPLOY_ENV

        '
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - id: deploy
      uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ env.DPLOYMENT_NAME }}
        parameters: ${{ env.PARAMETERFILE_NAME }}
        resourceGroupName: ${{ env.RESOUECE_GROUP_NAME }}
        template: ${{ env.TEMPLATE_NAME }}
name: Create azure infra for logic apps
'on':
  push:
    paths:
    - .github/workflows/logicapp_workflow.yaml
    - '*.json'
